### ISSUE TITLE
抖音可以支持一下

### ISSUE THREAD

**Issue by awen1988** [liliuwei/thinkphp-social#1]
抖音可以支持一下
https://open.douyin.com/platform

**Comment by liliuwei** [comment]
已新增抖音、小米授权登录，欢迎测试

**Comment by liliuwei** [comment]
> 抖音可以支持一下
> https://open.douyin.com/platform

已新增抖音、小米授权登录，欢迎测试

**Comment by awen1988** [comment]
感谢大佬。立马学习！

**Comment by liliuwei** [comment]
> 感谢大佬。立马学习！

有问题及时反馈
