### ISSUE TITLE
钉钉扫码登陆code网络请求报错

### ISSUE THREAD

**Issue by hepeichun** [liliuwei/thinkphp-social#4]
`

        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false); // 跳过证书检查
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false); // 跳过证书检查`

添加这个在http方法里面修复问题

**Comment by hepeichun** [comment]
建议作者将更证书放在一个目录，通过设置CURL的方式完成这块跳过证书检查，避免出现数据劫持篡改

**Comment by liliuwei** [comment]
> `
> 
> ```
>     curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false); // 跳过证书检查
>     curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false); // 跳过证书检查`
> ```
> 
> 添加这个在http方法里面修复问题
测试是没问题的
可以访问下面的地址试试：
http://www.huasuanwu.com/index/oauth/login/type/dingtalk

**Comment by hepeichun** [comment]
我访问的确没问题，您这边是不是在php.ini配置了

我看了您的代码

https://github.com/liliuwei/thinkphp-social/blob/aa0663998e2b6d8c713e63eb7c0f0cbf541df0e0/src/sdk/Dingtalk.php#L68
这块和其他部分不一样，你在dingtalk重新实现了http方法，这个方法里面的CURL没有做ssl的验证忽略，
所以有三种方案
代码可控部分
1. 忽略ssl验证
```     curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false); // 跳过证书检查
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false); // 跳过证书检查
```
2. 加载ssl的根证书进行验证，
```
        curl_setopt($ch, CURLOPT_SSLCERTTYPE, 'PEM');
        curl_setopt($ch, CURLOPT_SSLCERT, $sslCert);
        curl_setopt($ch, CURLOPT_SSLKEYTYPE, 'PEM');
        curl_setopt($ch, CURLOPT_SSLKEY, $sslKey);
```

php.ini配置部分

1. 指定根证书地址
`curl.cainfo=/path/to/downloaded/cacert.pem`

**Comment by hepeichun** [comment]
> > `
> > ```
> >     curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false); // 跳过证书检查
> >     curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false); // 跳过证书检查`
> > ```
> > 
> > 
> > 添加这个在http方法里面修复问题
> > 测试是没问题的
> > 可以访问下面的地址试试：
> > http://www.huasuanwu.com/index/oauth/login/type/dingtalk

我回复了您：https://github.com/liliuwei/thinkphp-social/issues/4#issuecomment-718514405

**Comment by liliuwei** [comment]
> > > `
> > > ```
> > >     curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false); // 跳过证书检查
> > >     curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false); // 跳过证书检查`
> > > ```
> > > 
> > > 
> > > 添加这个在http方法里面修复问题
> > > 测试是没问题的
> > > 可以访问下面的地址试试：
> > > http://www.huasuanwu.com/index/oauth/login/type/dingtalk
> 
> 我回复了您：[#4 (comment)](https://github.com/liliuwei/thinkphp-social/issues/4#issuecomment-718514405)
我没具体去测试问题出在哪里，但我更新了新的版本添加了跳过证书检查，使用新的版本吧

**Comment by hepeichun** [comment]
> > > > `
> > > > ```
> > > >     curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false); // 跳过证书检查
> > > >     curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false); // 跳过证书检查`
> > > > ```
> > > > 
> > > > 
> > > > 添加这个在http方法里面修复问题
> > > > 测试是没问题的
> > > > 可以访问下面的地址试试：
> > > > http://www.huasuanwu.com/index/oauth/login/type/dingtalk
> > 
> > 
> > 我回复了您：[#4 (comment)](https://github.com/liliuwei/thinkphp-social/issues/4#issuecomment-718514405)
> > 我没具体去测试问题出在哪里，但我更新了新的版本添加了跳过证书检查，使用新的版本吧

```
报错信息：Curl error: SSL certificate problem: unable to get local issuer certificate
```

我贴一下报错信息，感谢积极修复，在您认为合适的时候close这个问题吧
